sudo: required

services:
  - docker

matix:
  include:
    - language: java
      jdk:
        - openjdk11
      script:
        - echo "$DOCKERHUB_PWD" | docker login -u cuitaocrazy --password-stdin
        - cd oauth-gw
        - ./gradlew build
        - ./build-docker.sh
        - docker push cuitaocrazy/oauth-gw:latest
    - language: node_js
      node_js:
        - '14'
      script:
        - echo "$DOCKERHUB_PWD" | docker login -u cuitaocrazy --password-stdin
        - cd pm-resource-server
        - npm i
        - npm run build
        - npm run build-docker
        - docker push cuitaocrazy/pm-resource-server:latest
    - language: node_js
      node_js:
        - '14'
      script:
        - echo "$DOCKERHUB_PWD" | docker login -u cuitaocrazy --password-stdin
        - cd pm-web-app
        - npm i
        - npm run build
        - npm run build-docker
        - docker push cuitaocrazy/pm-web-app:latest
notifications:
  slack: yada-group:JEFsd2aNJz0M3uvn3Ris1c6C
