version: "1.0.13"
oauth:
  issuer: https://auth.lanxinpay.com/auth/realms/pm
  clientId: pm-app
  clientSecret: 0711ad1d-9053-4e3a-a6bb-db2b783e8eee
hostName: pm.lanxinpay.com
gwService:
  type: NodePort
  nodePort: 32659
mongoUrl: mongodb://mongodb-arbiter-headless.dbs/pm
