version: "1.0.25"
replicaCount: 2
oauth:
  issuer: https://auth.lanxinpay.com/auth/realms/pm
  clientId: pm-app
  clientSecret: 0711ad1d-9053-4e3a-a6bb-db2b783e8eee
hostName: pm.lanxinpay.com
gwService:
  type: NodePort
  nodePort: 32659
mongoUrl: mongodb://mongodb-arbiter-headless.dbs/pm
dnCronjob: 
  schedule: @weekly
  keycloak: 
    baseUrl: https://auth.lanxinpay.com/auth
    realmName: pm
    clientId: pm-dn
    clientSecret: 01110e3d-00c6-4145-a650-161a2315d0ef
  email:
    host: smtp.263.net
    port: 465
    user: rjeb_service@bjyada.com
    pass: password
    subject: 日报未提交通知
prostgres:
  user: pm
  password: pm
  host: postgresql-postgresql-ha-pgpool.dbs
  db: pm
  port: 5432
