version: "1.0.25"
replicaCount: 2
oauth:
  issuer: https://auth.lanxinpay.com/auth/realms/pm
  clientId: pm-app
  clientSecret: 0711ad1d-9053-4e3a-a6bb-db2b783e8eee
hostName: pm.lanxinpay.com
gwService:
  type: NodePort
  nodePort: 32659
mongoUrl: mongodb://mongodb-arbiter-headless.dbs/pm
pgHost: postgresql-postgresql-ha-pgpool.dbs
dnCronjob: 
  schedule: @weekly
  keycloak: 
    baseUrl: https://auth.lanxinpay.com/auth
    realmName: pm
    grantType: password
    clientId: pm-app
    clientSecret: 0711ad1d-9053-4e3a-a6bb-db2b783e8eee
    username: admin
    password: password
  email:
    host: smtp.263.net
    port: 465
    user: rjeb_service@bjyada.com
    pass: password
    subject: 日报未提交通知
