apiVersion: v1
kind: ServiceAccount
metadata:
  name: internal-kubectl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: internal-kubectl
  namespace: pm-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: pm-webhook
spec:
  selector:
    app: pm-webhook
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pm-webhook
spec:
  selector:
    matchLabels:
      app: pm-webhook
  template:
    metadata:
      labels:
        app: pm-webhook
    spec:
      serviceAccountName: internal-kubectl
      containers:
      - name: pm-webhook
        image: cuitaocrazy/pm-webhook:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
