apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pm-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dn
            image: pm-daily-notify:latest
            imagePullPolicy: IfNotPresent
            env: 
              - name: MONGODB_URL
                value: mongodb://mongodb-arbiter-headless.dbs/pm
              - name: EMAIL_HOST
                value: 10.2.53.51
          restartPolicy: Never