apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pm.gw.fullname" . }}
  labels:
    {{- include "pm.gw.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- toYaml .Values.oauth.config | nindent 4 }}