apiVersion: v1
kind: Service
metadata:
  name: {{ include "pm.gw.fullname" . }}
  labels:
    {{- include "pm.gw.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pm.gw.selectorLabels" . | nindent 4 }}
{{- if .Values.gwService.type }}
  type: {{ .Values.gwService.type }}
{{- end }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8090
    {{- if .Values.gwService.nodePort }}
      nodePort: {{ .Values.gwService.nodePort }}
    {{- end }}