apiVersion: v1
kind: Service
metadata:
  name: {{ include "pm.rs.fullname" . }}
  labels:
    {{- include "pm.rs.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pm.rs.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000